//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFromExcel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string Claimed_Malfunction { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> DateOfReceipt { get; set; }
        public string Warranty { get; set; }
        public string IdentifyFault { get; set; }
        public string WorkDone { get; set; }
        public string Engineer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
