//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectiveStatements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefectiveStatements()
        {
            this.DefectiveStatementRepairs = new HashSet<DefectiveStatementRepairs>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ClientId { get; set; }
        public int DocumentId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectiveStatementRepairs> DefectiveStatementRepairs { get; set; }
        public virtual ReceiptDocument ReceiptDocument { get; set; }
        public virtual Users Users { get; set; }
    }
}
