//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsOrder
    {
        public int OrderId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string PartName { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual ReceiptOfParts ReceiptOfParts { get; set; }
    }
}
