//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DefectiveStatements
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientId { get; set; }
        public int DocumentId { get; set; }
    }
}
